### ISSUE TITLE
Mock Data tracks.js has duplicate key

### ISSUE THREAD

**Issue by janagamap** [apollographql/odyssey-lift-off-part1#29]
In the useQuery hook section
https://odyssey.apollographql.com/lift-off-part1/the-usequery-hook

Doc has `<QueryResult error={error} loading={loading} data={data}>
  {data?.tracksForHome?.map((track) => (
    <TrackCard key={track.id} track={track} />
  ))}
</QueryResult>`

which causes react warning with below:
`
A warning is thrown at the end 
Encountered two children with the same key, `track_01`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in QueryResult (at tracks.js:32)
`

Where as the sandbox in the https://odyssey.apollographql.com/lift-off-part1/wrap-up 
with https://codesandbox.io/s/lift-off-part1-complete-mocks-w3319?from-embed=&file=/src/pages/tracks.js
has 
` <QueryResult error={error} loading={loading} data={data}>
        {data?.tracksForHome?.map((track, idx) => (
          <TrackCard key={`${track.id}-${idx}`} track={track} />
        ))}
      </QueryResult>`

Do we  need to correct the QueryResult to update the key? key={`${track.id}-${idx}`} 
Instruction needs to be updated.

**Comment by meganesu** [comment]
Hi @janagamap, thanks for reaching out!

Good eye. That warning is showing up because at this point we're still using mock data for the tracks (see [`final/server/src/index.js:9`](https://github.com/apollographql/odyssey-lift-off-part1/blob/main/final/server/src/index.js#L9))

If you continue on with the Lift-off series, in Lift-off II you'll connect your GraphQL server to an actual data source, which will pull in real track data (which has unique IDs for each track). That will make the warning go away. I'll also add a note to Lift-off I to let folks know that the warning is only a temporary issue.

Thanks again for reaching out, and for being part of our community! In the future, if you have questions, it's better to direct them to the [Odyssey topic in our community forum](https://community.apollographql.com/tags/c/help/6/odyssey).
